<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Deterministic>true</Deterministic>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Lers.Framework" Version="3.67.1" />
    <PackageReference Include="Lers.Plugins" Version="3.67.1" />
    <PackageReference Include="Lers.Utils" Version="3.67.1" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.10" />
  </ItemGroup>
</Project>